# Generated by Django 4.2.2 on 2023-07-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fee',
            new_name='coursefee',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='coursename',
        ),
    ]
